services:
  - type: web
    name: astrology-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main_ephe:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: .
    routes:
      - type: rewrite
        source: /*
        destination: / 